unique_ids:
  assets:
    standard-page.html: GXV4FPKKO4D22PECRXVWYDSYG75RZJFW
    theme.css: XTOLOHU3ZO6Q76XZNUCIV3SWGC3IJWAL
  forms:
    Form1: LVD2PBM5FM4EBW7MS3VJWAKBOPMJGGYO
  modules: {}
  scripts: {}
  server_modules: {}
